name: ROS2 CI

on:
  pull_request:
    branches:
      - 'foxy-humble'
  push:
    branches:
      - 'foxy-humble'
      - 'build-fix'

jobs:
  test_environment:
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - humble
        include:
          # Humble Hawksbill (May 2022 - May 2027)
          - docker_image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-ros-base-latest
            ros_distribution: humble
            ros_version: 2
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup dependencies
        run: |
          sudo apt update
          sudo apt install -y libusb-dev ros-humble-perception-pcl ros-humble-sensor-msgs-py ros-humble-tf-transformations ros-humble-joy ros-humble-rmw-cyclonedds-cpp ros-humble-rosidl-generator-dds-idl python3-colcon-common-extensions python-is-python3
          pip install transforms3d pyyaml          
      - name: build and test
        uses: ros-tooling/action-ros-ci@master
        with:
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: ""
          skip-tests: true
